// frontend/src/lib/components/Footer.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import facebookIcon from '@iconify/icons-mdi/facebook';
	import googleGmail from '@iconify/icons-mdi/gmail';
	import githubIcon from '@iconify/icons-mdi/github';
	import { fade } from 'svelte/transition';
</script>

<footer
	class="fixed bottom-0 flex w-screen items-center justify-between bg-primary-200 px-5 py-3 text-primary-700 shadow-lg"
	transition:fade
>
	<p class="text-5xl font-bold">cruX</p>
	<ul class="grid list-none grid-cols-1 items-center font-semibold sm:flex">
		<li class="mx-2 hover:text-primary-900">
			<a href="https://www.github.com/crux-bphc" rel="external" target="_blank">
				<Icon icon={githubIcon} width="35" />
			</a>
		</li>
		<li class="mx-2 hover:text-primary-900">
			<a href="mailto:crux@hyderabad.bits-pilani.ac.in" rel="external" target="_blank">
				<Icon icon={googleGmail} width="35" />
			</a>
		</li>
		<li class="mx-2 hover:text-primary-900">
			<a href="https://www.facebook.com/cruxbphc/" rel="external" target="_blank">
				<Icon icon={facebookIcon} width="35" />
			</a>
		</li>
	</ul>
</footer>

// frontend/src/components/Footer.tsx
import { ActionIcon, Flex, Group } from "@mantine/core";
import { IconBrandFacebook, IconBrandGithub, IconMail } from "@tabler/icons-react";

export default function Footer() {
  return (
    <footer
      style={{
        position: "fixed",
        bottom: "0",
        width: "80%",
        zIndex: -1,
        padding: "0.5em 1.5em",
      }}>
      <Flex justify="space-evenly">
        <p>
          Powered by <span style={{ color: "#164a9e", fontWeight: "bold" }}>cruX</span>
        </p>
        <Group>
          <ActionIcon component="a" variant="subtle" href="https://github.com/crux-bphc" aria-label="github">
            <IconBrandGithub color="#164a9e" />
          </ActionIcon>
          <ActionIcon component="a" variant="subtle" href="https://www.facebook.com/cruxbphc/" aria-label="facebook">
            <IconBrandFacebook color="#164a9e" />
          </ActionIcon>
          <ActionIcon component="a" variant="subtle" href="mailto:crux@hyderabad.bits-pilani.ac.in" aria-label="gmail">
            <IconMail color="#164a9e" />
          </ActionIcon>
        </Group>
      </Flex>
    </footer>
  );
}
